config/routes.rb
Rails.application.routes.draw do
  
  
  resources :sessions, only: [:new, :index]
  get "login", to: 'sessions#new'
  root 'chatroom#index'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
    has_many :message
    validates :username, uniqueness: true, presence: true, length: {minimum: 3, maximum: 15}
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
    
    def require_user
        if !logged_in?
            flash[:error] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user 
    def index
        @messages = Message.all
        @message = Message.new
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.message.build(message_params)
        if message.save
            redirect_to root_path
        end
    end

    private

    def message_params
        params.require(:message).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]
    
    def new
        
    end
    

    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to root_path
        else
            flash.now[:error] = "There was something wrong with your login information"
            render 'new',  status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have successfully logged out"
        redirect_to login_path
    end

    private
    
    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are already logged in"
            redirect_to root_path
        end
            
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h1> Welcome to the message-me index</h1>
<h4 class="ui center aligned medium icon header">
  <i class="circular blue coffee icon"></i>
  say something
</h4>

<div class = "ui two column grid">
    
    <div class = "four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                    <a class="active item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
    
    <div class = " twelve wide column">
        <div class="ui fluid raised card chatbox">

            <div class="content">
                <div class="ui feed">
                
                    <%@messages.each do |m|%>
                        <div class="event">
                            <div class="content">
                                <div class="summary">
                                    <%= m.user.username%>:
                                    <%= m.body %></br>
                                </div>
                            </div>
                        </div>
                    <%end%>
                </div>
            </div>

            <div class="extra content">
            <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path) do |f| %>
                <div class="field">
                    <div class="ui fluid icon input">
                        <%= f.text_field :body %>
                        <%= f.button '<i class="bordered inverted blue icon send"></i>'.html_safe %>
                    </div>
                </div>
            <%end%>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
<div class="ui <%=message_type%> message transition">
  <i class="close icon" onclick="this.parentElement.style.display='none';"></i>
  <div class="header">
     <%= message_content %>
  </div>
</div>
<%end%>

app/views/layouts/_navigation.html.erb
<div class="ui small menu inverted">
    <div class = "ui container">
        
        <%= link_to "Chatroom", root_path,class: "item "%>
        <a class="item">
          Messages
        </a>
        <div class="right menu">
            <div class="ui dropdown item">
                Account <i class="dropdown icon"></i>
                <div class="menu">
                    <%if logged_in? %>
                        <%= link_to "log out", logout_path, method: :delete, class: "item "%>
                    <%else%>   
                        <%= link_to "log in(#)", login_path,class: "item "%>
                    <%end%> 
                    
                </div>
            </div>
            <% if !logged_in? %>
                <div class="item">
                    <%= link_to "sign up", login_path, class: "ui primary button"%>
                </div>
            <%end%>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
   <%= render 'layouts/navigation' %>
    <div class = "ui container">
    <%= render 'layouts/messages'%>
     <%= yield %>
    </div>
  </body>
</html>